AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: CD Assignment 2 Lambda
Resources:
  CDDemoLambda:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./LambdaCode
      Description: "Lambda function for CD Assignment 2"
      MemorySize: 128
      Timeout: 30
      Role: "arn:aws:iam::375241913406:role/Cloudformation-Service-Role-Hussain"
      Events:
        getAZsAPI:
          Type: Api
          Properties:
            Path: /getazs
            Method: get
      Environment:
        Variables:
          REGION: us-east-1
